# Generated by Django 4.1.7 on 2023-08-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0005_campaignquestionresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaignquestionresponse',
        ),
    ]
