# Generated by Django 4.1.7 on 2023-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0006_delete_campaignquestionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaignquestionresponse',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(db_column='response', max_length=2000)),
            ],
            options={
                'db_table': 'campaignquestionresponse',
                'managed': False,
            },
        ),
    ]
