# Generated by Django 4.1.7 on 2023-08-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0007_campaignquestionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, db_column='email', max_length=255),
        ),
    ]
