# Generated by Django 4.1.7 on 2023-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0008_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvideoid',
            name='userID',
            field=models.CharField(db_column='userID', max_length=250, null=True),
        ),
    ]
